//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invest.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPrice
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> CapitalPrice { get; set; }
        public Nullable<decimal> IncomePrice { get; set; }
        public Nullable<decimal> TRPrice { get; set; }
        public bool IsDeleted { get; set; }
        public string ImportSource { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
