//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invest.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ApprovelProductLists = new HashSet<ApprovelProductList>();
            this.ModelVersions = new HashSet<ModelVersion>();
            this.ModelVersions1 = new HashSet<ModelVersion>();
            this.ProductBrokers = new HashSet<ProductBroker>();
            this.ProductMonthReturns = new HashSet<ProductMonthReturn>();
            this.ProductPrices = new HashSet<ProductPrice>();
            this.ProductVersions = new HashSet<ProductVersion>();
            this.ProductVersions1 = new HashSet<ProductVersion>();
            this.ProductVersions2 = new HashSet<ProductVersion>();
            this.RateLists = new HashSet<RateList>();
            this.Securities = new HashSet<Security>();
            this.Securities1 = new HashSet<Security>();
        }
    
        public int ProductID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public Nullable<int> IndexTypeId { get; set; }
        public Nullable<int> AssetClassId { get; set; }
        public string ProductAPIR { get; set; }
        public string ProductISIN { get; set; }
        public Nullable<int> InstitutionId { get; set; }
        public Nullable<int> MarketId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> SubAssetClassId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> InceptionDate { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ApprovelProductList> ApprovelProductLists { get; set; }
        public virtual AssetClass AssetClass { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual IndexType IndexType { get; set; }
        public virtual Institution Institution { get; set; }
        public virtual Market Market { get; set; }
        public virtual ICollection<ModelVersion> ModelVersions { get; set; }
        public virtual ICollection<ModelVersion> ModelVersions1 { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual Region Region { get; set; }
        public virtual SecurityStatu SecurityStatu { get; set; }
        public virtual SubAssetClass SubAssetClass { get; set; }
        public virtual ICollection<ProductBroker> ProductBrokers { get; set; }
        public virtual ICollection<ProductMonthReturn> ProductMonthReturns { get; set; }
        public virtual ICollection<ProductPrice> ProductPrices { get; set; }
        public virtual ProductReturn ProductReturn { get; set; }
        public virtual ProductStatistic ProductStatistic { get; set; }
        public virtual ICollection<ProductVersion> ProductVersions { get; set; }
        public virtual ICollection<ProductVersion> ProductVersions1 { get; set; }
        public virtual ICollection<ProductVersion> ProductVersions2 { get; set; }
        public virtual ICollection<RateList> RateLists { get; set; }
        public virtual ICollection<Security> Securities { get; set; }
        public virtual ICollection<Security> Securities1 { get; set; }
    }
}
