//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invest.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVersion
    {
        public ProductVersion()
        {
            this.ModelDetails = new HashSet<ModelDetail>();
            this.ProductAssociations = new HashSet<ProductAssociation>();
            this.ProductVersionInvestmentPrograms = new HashSet<ProductVersionInvestmentProgram>();
            this.ProductVersionInvestmentProgramTemplates = new HashSet<ProductVersionInvestmentProgramTemplate>();
        }
    
        public int ProductVersionID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public bool IsPriced { get; set; }
        public Nullable<int> PricingSourceID { get; set; }
        public Nullable<decimal> SecurityMER { get; set; }
        public Nullable<decimal> ProductMER { get; set; }
        public Nullable<int> MajorVersion { get; set; }
        public Nullable<int> MinorVersion { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> ProductReimbursable { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> PrimaryBenchmarkProductID { get; set; }
        public Nullable<int> SecondaryBenchmarkProductID { get; set; }
        public Nullable<int> PrimaryPriceTypeId { get; set; }
        public Nullable<decimal> TargetReturnRate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> SecondaryPriceTypeId { get; set; }
    
        public virtual ICollection<ModelDetail> ModelDetails { get; set; }
        public virtual PriceType PriceType { get; set; }
        public virtual PriceType PriceType1 { get; set; }
        public virtual PricingSource PricingSource { get; set; }
        public virtual Product Product { get; set; }
        public virtual Product Product1 { get; set; }
        public virtual Product Product2 { get; set; }
        public virtual ICollection<ProductAssociation> ProductAssociations { get; set; }
        public virtual SecurityStatu SecurityStatu { get; set; }
        public virtual ICollection<ProductVersionInvestmentProgram> ProductVersionInvestmentPrograms { get; set; }
        public virtual ICollection<ProductVersionInvestmentProgramTemplate> ProductVersionInvestmentProgramTemplates { get; set; }
    }
}
