//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invest.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityPrice
    {
        public SecurityPrice()
        {
            this.NAVSecurityAttachments = new HashSet<NAVSecurityAttachment>();
        }
    
        public int Id { get; set; }
        public int SecurityId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public decimal UnitPrice { get; set; }
        public Nullable<decimal> PriceNAV { get; set; }
        public Nullable<decimal> PricePUR { get; set; }
        public Nullable<decimal> InterestRate { get; set; }
        public Nullable<int> ValuationTypeId { get; set; }
        public string Valuer { get; set; }
        public string Attachment { get; set; }
        public bool IsDeleted { get; set; }
        public string ImportSource { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual ICollection<NAVSecurityAttachment> NAVSecurityAttachments { get; set; }
        public virtual Security Security { get; set; }
        public virtual ValuationType ValuationType { get; set; }
    }
}
