//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invest.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Security
    {
        public Security()
        {
            this.ApprovelProductLists = new HashSet<ApprovelProductList>();
            this.DistributionDividendDetails = new HashSet<DistributionDividendDetail>();
            this.InvestmentProgramConstraints = new HashSet<InvestmentProgramConstraint>();
            this.InvestmentProgramConstraints1 = new HashSet<InvestmentProgramConstraint>();
            this.InvestmentProgramConstraintTemplates = new HashSet<InvestmentProgramConstraintTemplate>();
            this.InvestmentProgramConstraintTemplates1 = new HashSet<InvestmentProgramConstraintTemplate>();
            this.InvestmentProgramDefaultSecurities = new HashSet<InvestmentProgramDefaultSecurity>();
            this.InvestmentProgramDefaultSecuritiesTemplates = new HashSet<InvestmentProgramDefaultSecuritiesTemplate>();
            this.LinkNAVSecurities = new HashSet<LinkNAVSecurity>();
            this.ModelDetails = new HashSet<ModelDetail>();
            this.NAVSecurityPropertyDetails = new HashSet<NAVSecurityPropertyDetail>();
            this.OptionsDetails = new HashSet<OptionsDetail>();
            this.ProductAssociations = new HashSet<ProductAssociation>();
            this.ScreenDetails = new HashSet<ScreenDetail>();
            this.SecuritiesInvestmentPrograms = new HashSet<SecuritiesInvestmentProgram>();
            this.SecuritiesInvestmentProgramTemplates = new HashSet<SecuritiesInvestmentProgramTemplate>();
            this.SecurityAssetClasses = new HashSet<SecurityAssetClass>();
            this.SecurityHoldingDetails = new HashSet<SecurityHoldingDetail>();
            this.SecurityListDetails = new HashSet<SecurityListDetail>();
            this.SecurityPrices = new HashSet<SecurityPrice>();
            this.TermDeposits = new HashSet<TermDeposit>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string APIRCode { get; set; }
        public string ISINCode { get; set; }
        public Nullable<int> SecurityCategoryId { get; set; }
        public Nullable<int> SecurityTypeId { get; set; }
        public Nullable<int> UnitisedId { get; set; }
        public Nullable<int> MarketId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> SubAssetClassId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> GICSId { get; set; }
        public Nullable<int> GICSTypeId { get; set; }
        public Nullable<int> RatingId { get; set; }
        public Nullable<int> SecurityStatusId { get; set; }
        public Nullable<decimal> UnitsHeld { get; set; }
        public Nullable<int> PricingSourceId { get; set; }
        public Nullable<int> DistributionTypeId { get; set; }
        public Nullable<int> DistributionFrequencyId { get; set; }
        public Nullable<decimal> ExpenseRatio { get; set; }
        public Nullable<int> Liquidity { get; set; }
        public string PropertyDetails { get; set; }
        public bool IsDeleted { get; set; }
        public string Description { get; set; }
        public Nullable<int> PrimaryBenchmarkProductID { get; set; }
        public Nullable<int> SecondaryBenchmarkProductID { get; set; }
        public Nullable<int> PrimaryPriceTypeId { get; set; }
        public Nullable<System.DateTime> InceptionDate { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public Nullable<int> SecondaryPriceTypeId { get; set; }
    
        public virtual ICollection<ApprovelProductList> ApprovelProductLists { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual DistibutionFrequency DistibutionFrequency { get; set; }
        public virtual ICollection<DistributionDividendDetail> DistributionDividendDetails { get; set; }
        public virtual DistributionType DistributionType { get; set; }
        public virtual GIC GIC { get; set; }
        public virtual GICSType GICSType { get; set; }
        public virtual ICollection<InvestmentProgramConstraint> InvestmentProgramConstraints { get; set; }
        public virtual ICollection<InvestmentProgramConstraint> InvestmentProgramConstraints1 { get; set; }
        public virtual ICollection<InvestmentProgramConstraintTemplate> InvestmentProgramConstraintTemplates { get; set; }
        public virtual ICollection<InvestmentProgramConstraintTemplate> InvestmentProgramConstraintTemplates1 { get; set; }
        public virtual ICollection<InvestmentProgramDefaultSecurity> InvestmentProgramDefaultSecurities { get; set; }
        public virtual ICollection<InvestmentProgramDefaultSecuritiesTemplate> InvestmentProgramDefaultSecuritiesTemplates { get; set; }
        public virtual ICollection<LinkNAVSecurity> LinkNAVSecurities { get; set; }
        public virtual Market Market { get; set; }
        public virtual ICollection<ModelDetail> ModelDetails { get; set; }
        public virtual ICollection<NAVSecurityPropertyDetail> NAVSecurityPropertyDetails { get; set; }
        public virtual ICollection<OptionsDetail> OptionsDetails { get; set; }
        public virtual PriceType PriceType { get; set; }
        public virtual PriceType PriceType1 { get; set; }
        public virtual PricingSource PricingSource { get; set; }
        public virtual Product Product { get; set; }
        public virtual Product Product1 { get; set; }
        public virtual ICollection<ProductAssociation> ProductAssociations { get; set; }
        public virtual Rating Rating { get; set; }
        public virtual Region Region { get; set; }
        public virtual ICollection<ScreenDetail> ScreenDetails { get; set; }
        public virtual ICollection<SecuritiesInvestmentProgram> SecuritiesInvestmentPrograms { get; set; }
        public virtual ICollection<SecuritiesInvestmentProgramTemplate> SecuritiesInvestmentProgramTemplates { get; set; }
        public virtual SecurityCategory SecurityCategory { get; set; }
        public virtual SecurityStatu SecurityStatu { get; set; }
        public virtual SecurityType SecurityType { get; set; }
        public virtual SubAssetClass SubAssetClass { get; set; }
        public virtual Unitised Unitised { get; set; }
        public virtual ICollection<SecurityAssetClass> SecurityAssetClasses { get; set; }
        public virtual ICollection<SecurityHoldingDetail> SecurityHoldingDetails { get; set; }
        public virtual ICollection<SecurityListDetail> SecurityListDetails { get; set; }
        public virtual ICollection<SecurityPrice> SecurityPrices { get; set; }
        public virtual SecurityReturn SecurityReturn { get; set; }
        public virtual ICollection<TermDeposit> TermDeposits { get; set; }
    }
}
